let UserType = {
  SET_USER:"SET_USER",
  SET_ADDRESSES:"SET_ADDRESSES",
  SET_ORDERS:"SET_ORDERS",
  SET_LOGOUT:"SET_LOGOUT",
  SET_NOTIFICATION_TOKEN:"SET_NOTIFICATION_TOKEN"
};

export default UserType;
