let OrdersType = {
    SET_ORDERS_ITEMS:"SET_ORDERS_ITEMS",
    SET_SELECTED_ADDRESS:"SET_SELECTED_ADDRESS",
    SET_ORDER_DISCOUNT_CODE:"SET_ORDER_DISCOUNT_CODE",
    RESET_ORDERS:"RESET_ORDERS"
}

export default OrdersType;