let ItemsType = {
    SET_SELECT_FOR_YOU_ITEMS_FIRST:"SET_SELECT_FOR_YOU_ITEMS_FIRST",
    SET_SELECT_FOR_YOU_ITEMS_SECOND:"SET_SELECT_FOR_YOU_ITEMS_SECOND",
    SET_NEW_ITEMS:"SET_NEW_ITEMS",
    SET_CATEGORIES_WITH_ITEMS:"SET_CATEGORIES_WITH_ITEMS",
    SET_WISHLIST_ITEMS:"SET_WISHLIST_ITEMS",
    SET_ADS:"SET_ADS"
  }
  
  export default ItemsType;